[project]
name = "dns-mapping"
version = "0.1.0"
description = "Mapping mail server dependencies using DNS data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [ "pydig" , "pandas", "ipwhois", "openpyxl" ]
